include: package:lints/recommended.yaml

analyzer:
  exclude:
    - apps/**
    - packages/phoenix_ui/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    always_declare_return_types: true
